package com.example.cheque_clearing_system;

import org.springframework.stereotype.Controller; import org.springframework.ui.Model; import org.springframework.web.bind.annotation.*; import jakarta.servlet.http.HttpSession;
import java.time.LocalDate; import java.util.*; import java.util.stream.Collectors;

@Controller public class HomeController {
 private final UserRepository users; private final ChequeRepository cheques; private final AuditLogRepository audits; private final NotificationRepository notifications;
 public HomeController(UserRepository u,ChequeRepository c,AuditLogRepository a,NotificationRepository n){users=u;cheques=c;audits=a;notifications=n;}
 @GetMapping("/") public String home(){return "index";}
 @GetMapping("/customer-login") public String customerLogin(){return "customer-login";}
 @PostMapping("/customer-login") public String customerLoginProcess(@RequestParam String username,@RequestParam String password,HttpSession s,Model m){return login(username,password,"CUSTOMER",s,m,"customer-login");}
 @GetMapping("/admin-login") public String adminLogin(){return "admin-login";}
 @PostMapping("/admin-login") public String adminLoginProcess(@RequestParam String username,@RequestParam String password,HttpSession s,Model m){return login(username,password,"ADMIN",s,m,"admin-login");}
 private String login(String un,String pw,String role,HttpSession s,Model m,String view){var u=users.findByUsername(un); if(u.isPresent()&&u.get().getPassword().equals(pw)&&role.equals(u.get().getRole())){s.setAttribute("userId",u.get().getId());s.setAttribute("role",role); audits.save(new AuditLog(un,"LOGIN",null,"Successful login")); return "redirect:/"+(role.equals("ADMIN")?"admin-dashboard":"customer-dashboard");} m.addAttribute("error","Invalid credentials or role."); return view;}
 @GetMapping("/logout") public String logout(HttpSession s){s.invalidate();return "redirect:/";}
 private User current(HttpSession s){Object id=s.getAttribute("userId"); if(id==null)return null; return users.findById((Long)id).orElse(null);}
 private String guard(HttpSession s,String role){return role.equals(s.getAttribute("role"))?null:"redirect:/"+role.toLowerCase()+"-login";}
 @GetMapping("/customer-dashboard") public String customerDashboard(HttpSession s,Model m){User u=current(s);if(u==null)return "redirect:/customer-login";m.addAttribute("user",u);m.addAttribute("notifications",notifications.findByUserOrderByCreatedAtDesc(u).stream().limit(5).collect(Collectors.toList()));m.addAttribute("unread",notifications.countByUserAndReadFlagFalse(u));return "customer-dashboard";}
 @GetMapping("/submit-cheque") public String submitCheque(HttpSession s){return current(s)==null?"redirect:/customer-login":"submit-cheque";}
 @PostMapping("/submit-cheque") public String submitChequeProcess(@RequestParam String chequeNumber,@RequestParam String accountNumber,@RequestParam Double amount,@RequestParam String bankName,@RequestParam String clearingBank,@RequestParam LocalDate chequeDate,HttpSession s,Model m){User u=current(s);if(u==null)return "redirect:/customer-login"; if(cheques.existsByChequeNumberAndBankName(chequeNumber,bankName)){m.addAttribute("error","Duplicate cheque number for this bank.");return "submit-cheque";} Cheque c=new Cheque(chequeNumber,accountNumber,amount,bankName,chequeDate,"SUBMITTED",u);c.setClearingBank(clearingBank); if(amount >= 100000){c.setFraudFlag(true);c.setFraudReason("High-value cheque requires enhanced review");} cheques.save(c); audits.save(new AuditLog(u.getUsername(),"SUBMIT_CHEQUE",c.getId(),"Cheque submitted to "+clearingBank)); return "redirect:/my-cheques";}
 @GetMapping("/my-cheques") public String myCheques(@RequestParam(required=false) String q,@RequestParam(required=false) String status,HttpSession s,Model m){User u=current(s);if(u==null)return "redirect:/customer-login";List<Cheque> list=cheques.findBySubmittedBy(u);if(q!=null&&!q.isBlank())list=list.stream().filter(c->(c.getChequeNumber()+" "+c.getBankName()+" "+c.getAccountNumber()).toLowerCase().contains(q.toLowerCase())).toList();if(status!=null&&!status.isBlank())list=list.stream().filter(c->status.equals(c.getStatus())).toList();m.addAttribute("cheques",list);m.addAttribute("q",q);m.addAttribute("status",status);return "my-cheques";}
 @GetMapping("/admin-dashboard") public String adminDashboard(HttpSession s,Model m){if(!"ADMIN".equals(s.getAttribute("role")))return "redirect:/admin-login";m.addAttribute("total",cheques.count());m.addAttribute("submitted",cheques.countByStatus("SUBMITTED"));m.addAttribute("approved",cheques.countByStatus("APPROVED"));m.addAttribute("rejected",cheques.countByStatus("REJECTED"));m.addAttribute("cleared",cheques.countByStatus("CLEARED"));m.addAttribute("fraud",cheques.countByFraudFlagTrue());return "admin-dashboard";}
 @GetMapping("/admin/cheques") public String adminCheques(@RequestParam(required=false)String q,@RequestParam(required=false)String status,HttpSession s,Model m){if(!"ADMIN".equals(s.getAttribute("role")))return "redirect:/admin-login";List<Cheque> list=cheques.findAll();if(q!=null&&!q.isBlank())list=list.stream().filter(c->(c.getChequeNumber()+" "+c.getBankName()+" "+c.getAccountNumber()).toLowerCase().contains(q.toLowerCase())).toList();if(status!=null&&!status.isBlank())list=list.stream().filter(c->status.equals(c.getStatus())).toList();m.addAttribute("cheques",list);m.addAttribute("q",q);m.addAttribute("status",status);return "admin-cheques";}
 @PostMapping("/admin/cheques/{id}/decision") public String decision(@PathVariable Long id,@RequestParam String decision,@RequestParam(required=false)String reason,HttpSession s){if(!"ADMIN".equals(s.getAttribute("role")))return "redirect:/admin-login";Cheque c=cheques.findById(id).orElseThrow();String old=c.getStatus();if("APPROVE".equals(decision)){c.setStatus("APPROVED");}else if("REJECT".equals(decision)){c.setStatus("REJECTED");c.setRejectionReason(reason);}else if("CLEAR".equals(decision)&&"APPROVED".equals(c.getStatus())){c.setStatus("CLEARED");}else if("RETURN".equals(decision)&&"SUBMITTED".equals(c.getStatus())){c.setStatus("IN_REVIEW");}cheques.save(c);User u=c.getSubmittedBy();String msg="Cheque "+c.getChequeNumber()+" changed from "+old+" to "+c.getStatus()+(c.getRejectionReason()!=null?". Reason: "+c.getRejectionReason():"");notifications.save(new Notification(u,msg));audits.save(new AuditLog(current(s).getUsername(),"STATUS_CHANGE",c.getId(),msg));return "redirect:/admin/cheques";}
 @GetMapping("/admin/audit") public String audit(HttpSession s,Model m){if(!"ADMIN".equals(s.getAttribute("role")))return "redirect:/admin-login";m.addAttribute("logs",audits.findTop200ByOrderByTimestampDesc());return "audit";}
 @GetMapping("/admin/report") public void report(HttpSession s,jakarta.servlet.http.HttpServletResponse response)throws Exception{if(!"ADMIN".equals(s.getAttribute("role"))){response.sendRedirect("/admin-login");return;}response.setContentType("application/pdf");response.setHeader("Content-Disposition","attachment; filename=cheque-report.pdf");var doc=new com.lowagie.text.Document();com.lowagie.text.pdf.PdfWriter.getInstance(doc,response.getOutputStream());doc.open();doc.add(new com.lowagie.text.Paragraph("Cheque Clearing Report"));doc.add(new com.lowagie.text.Paragraph("Generated: "+LocalDate.now()));doc.add(new com.lowagie.text.Paragraph("Total: "+cheques.count()+" | Submitted: "+cheques.countByStatus("SUBMITTED")+" | Approved: "+cheques.countByStatus("APPROVED")+" | Rejected: "+cheques.countByStatus("REJECTED")+" | Cleared: "+cheques.countByStatus("CLEARED")+" | Fraud flags: "+cheques.countByFraudFlagTrue()));doc.add(new com.lowagie.text.Paragraph(" "));for(Cheque c:cheques.findAll())doc.add(new com.lowagie.text.Paragraph("#"+c.getChequeNumber()+" | "+c.getBankName()+" | "+c.getAmount()+" | "+c.getStatus()+" | fraud="+c.isFraudFlag()));doc.close();}
}
